// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogPostDocumentDataSlicesSlice = never;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Data do Post field in *Blog Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.blogPostDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  blogPostDate: prismic.DateField;

  /**
   * Nome do Autor field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.authorName
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  authorName: prismic.KeyTextField;

  /**
   * Foto do Autor field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.authorPicture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  authorPicture: prismic.ImageField<never>;

  /**
   * Destaque field in *Blog Post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blogPost.highlight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  highlight: prismic.BooleanField;

  /**
   * Imagem do Post field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.postImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  postImage: prismic.ImageField<never>;

  /**
   * Título do Post field in *Blog Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título do Post
   * - **API ID Path**: blogPost.postTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  postTitle: prismic.TitleField;

  /**
   * Sumário do Post field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sumário do Post
   * - **API ID Path**: blogPost.postSummary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  postSummary: prismic.RichTextField;

  /**
   * Descrição do Post field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do Post
   * - **API ID Path**: blogPost.postDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  postDescription: prismic.RichTextField;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogPost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogPost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogPost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blogPost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blogPost",
    Lang
  >;

type ContactDocumentDataSlicesSlice = SocialMediaContactPageSlice;

/**
 * Content for Contato documents
 */
interface ContactDocumentData {
  /**
   * Texto Branco do Título (Início) field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.pageTitlePrefix
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitlePrefix: prismic.RichTextField;

  /**
   * Texto Amarelo do Título (meio) field in *Contato*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título da Página
   * - **API ID Path**: contact.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitle: prismic.TitleField;

  /**
   * Texto Branco do Título (final) field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.pageTitleSufix
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitleSufix: prismic.RichTextField;

  /**
   * Descrição da Página field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da Página
   * - **API ID Path**: contact.pageDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageDescription: prismic.RichTextField;

  /**
   * Geolocalização (Para Google Maps) field in *Contato*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.geopoint
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  geopoint: prismic.GeoPointField;

  /**
   * Endereço field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Endereço
   * - **API ID Path**: contact.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Endereço de E-mail field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Endereço de E-mail
   * - **API ID Path**: contact.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * Telefone field in *Contato*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Telefone
   * - **API ID Path**: contact.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;

  /**
   * Slice Zone field in *Contato*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contato document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type FaqDocumentDataSlicesSlice = FaqQuestionSlice;

/**
 * Content for Faq documents
 */
interface FaqDocumentData {
  /**
   * Título da Página field in *Faq*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título da Página
   * - **API ID Path**: faq.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitle: prismic.TitleField;

  /**
   * Slice Zone field in *Faq*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Description field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Faq*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Faq*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Faq document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

type FooterDocumentDataSlicesSlice = FooterLinkSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo Clara Footer field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerLogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footerLogo: prismic.ImageField<never>;

  /**
   * Endereco field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type GlobalNavbarDocumentDataSlicesSlice = FooterLinkSlice;

/**
 * Content for Barra de Navegação documents
 */
interface GlobalNavbarDocumentData {
  /**
   * Logo Escura Navbar field in *Barra de Navegação*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globalNavbar.navbarLogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  navbarLogo: prismic.ImageField<never>;

  /**
   * Logo Clara Navbar field in *Barra de Navegação*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: globalNavbar.navbarLogoLight
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  navbarLogoLight: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Barra de Navegação*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: globalNavbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GlobalNavbarDocumentDataSlicesSlice>;
}

/**
 * Barra de Navegação document from Prismic
 *
 * - **API ID**: `globalNavbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalNavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalNavbarDocumentData>,
    "globalNavbar",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | HeroAnimatedImageSlice
  | AboutUsArchitectSlice
  | MetodologyCardsSlice
  | AboutUsItemSlice
  | ServicesSlicesSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Texto Branco no Título field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto Branco no Título
   * - **API ID Path**: home.whiteTitleText
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whiteTitleText: prismic.KeyTextField;

  /**
   * Texto Amarelo no Título field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto Amarelo no Título
   * - **API ID Path**: home.yellowTitleText
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yellowTitleText: prismic.KeyTextField;

  /**
   * Descrição Hero field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Hero
   * - **API ID Path**: home.heroDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heroDescription: prismic.RichTextField;

  /**
   * Imagem Hero 1 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.heroImage1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroImage1: prismic.ImageField<never>;

  /**
   * Título Serviços field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título Serviços
   * - **API ID Path**: home.servicesTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  servicesTitle: prismic.TitleField;

  /**
   * Descrição Serviços field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Serviços
   * - **API ID Path**: home.servicesDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  servicesDescription: prismic.RichTextField;

  /**
   * Título de Metodologia field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título Metodologia
   * - **API ID Path**: home.metodologyTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  metodologyTitle: prismic.TitleField;

  /**
   * Descrição de Metodologia field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Metodologia
   * - **API ID Path**: home.metodologyDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  metodologyDescription: prismic.RichTextField;

  /**
   * Texto do Lado de Metodologia field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto do Lado de Metodologia
   * - **API ID Path**: home.metodologyAsideText
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  metodologyAsideText: prismic.RichTextField;

  /**
   * Título Portfólio field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título Portfólio
   * - **API ID Path**: home.portfolioTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  portfolioTitle: prismic.TitleField;

  /**
   * Descrição Portfólio field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Portfólio
   * - **API ID Path**: home.portfolioDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  portfolioDescription: prismic.RichTextField;

  /**
   * Título Quem Somos field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título Quem Somos
   * - **API ID Path**: home.aboutUsTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  aboutUsTitle: prismic.TitleField;

  /**
   * Descrição Quem Somos field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Quem Somos
   * - **API ID Path**: home.aboutUsDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  aboutUsDescription: prismic.RichTextField;

  /**
   * Imagem Quem Somos field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.aboutUsImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aboutUsImage: prismic.ImageField<never>;

  /**
   * Título Call to Action field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título Call to Action
   * - **API ID Path**: home.callToActionTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  callToActionTitle: prismic.TitleField;

  /**
   * Descrição Call to Action field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Call to Action
   * - **API ID Path**: home.callToActionDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  callToActionDescription: prismic.RichTextField;

  /**
   * Logo Encurtada Call to Action field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.callToActionLogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  callToActionLogo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MaterialDocumentDataSlicesSlice = MaterialItemSlice;

/**
 * Content for Material documents
 */
interface MaterialDocumentData {
  /**
   * Título da Página field in *Material*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título da Página
   * - **API ID Path**: material.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitle: prismic.TitleField;

  /**
   * Descrição da Página field in *Material*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da Página
   * - **API ID Path**: material.pageDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageDescription: prismic.RichTextField;

  /**
   * Slice Zone field in *Material*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: material.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MaterialDocumentDataSlicesSlice> /**
   * Meta Description field in *Material*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: material.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Material*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: material.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Material*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: material.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Material document from Prismic
 *
 * - **API ID**: `material`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MaterialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MaterialDocumentData>,
    "material",
    Lang
  >;

type PortfolioDocumentDataSlicesSlice = StatementsSlice;

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Título da Página field in *Portfolio*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título da Página
   * - **API ID Path**: portfolio.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitle: prismic.TitleField;

  /**
   * Descrição da Página field in *Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da Página
   * - **API ID Path**: portfolio.pageDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageDescription: prismic.RichTextField;

  /**
   * Título Depoimentos field in *Portfolio*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título Depoimentos
   * - **API ID Path**: portfolio.statementTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  statementTitle: prismic.TitleField;

  /**
   * Descrição Depoimentos field in *Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição Depoimentos
   * - **API ID Path**: portfolio.statementDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  statementDescription: prismic.RichTextField;

  /**
   * Call to Action Depoimentos field in *Portfolio*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Call to Action Depoimentos
   * - **API ID Path**: portfolio.statementCallToAction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  statementCallToAction: prismic.RichTextField;

  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortfolioDocumentData>,
    "portfolio",
    Lang
  >;

type PortfolioPostDocumentDataSlicesSlice = PortfolioItemImageSlice;

/**
 * Content for Portfolio Post documents
 */
interface PortfolioPostDocumentData {
  /**
   * Título do Item de Portfólio field in *Portfolio Post*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título do Item de Portfólio
   * - **API ID Path**: portfolioPost.portfolioItemTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  portfolioItemTitle: prismic.TitleField;

  /**
   * Sumário do Item de Portfóilio field in *Portfolio Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sumário do Item de Portfóilio
   * - **API ID Path**: portfolioPost.portfolioItemSummary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  portfolioItemSummary: prismic.RichTextField;

  /**
   * Data do Item de Portfólio field in *Portfolio Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Data do Item de Portfólio
   * - **API ID Path**: portfolioPost.portfolioItemDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  portfolioItemDate: prismic.DateField;

  /**
   * Principal Foto do Item de Portfólio field in *Portfolio Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioPost.portfolioItemMainPicture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolioItemMainPicture: prismic.ImageField<never>;

  /**
   * Descrição do Item de Portfólio field in *Portfolio Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do Item de Portfólio
   * - **API ID Path**: portfolioPost.portfolioItemDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  portfolioItemDescription: prismic.RichTextField;

  /**
   * Tipo do Projeto field in *Portfolio Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Tipo do Projeto
   * - **API ID Path**: portfolioPost.projectType
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projectType: prismic.RichTextField;

  /**
   * Área do Projeto field in *Portfolio Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Área do Projeto
   * - **API ID Path**: portfolioPost.projectArea
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projectArea: prismic.RichTextField;

  /**
   * Objetivos do Projeto field in *Portfolio Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Objetivos do Projeto
   * - **API ID Path**: portfolioPost.projectObjectives
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projectObjectives: prismic.RichTextField;

  /**
   * Benefícios do Projeto field in *Portfolio Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Benefícios do Projeto
   * - **API ID Path**: portfolioPost.projectBenefits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projectBenefits: prismic.RichTextField;

  /**
   * Slice Zone field in *Portfolio Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioPost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Portfolio Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolioPost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfolio Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolioPost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Portfolio Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolioPost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Portfolio Post document from Prismic
 *
 * - **API ID**: `portfolioPost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PortfolioPostDocumentData>,
    "portfolioPost",
    Lang
  >;

type ServicesDocumentDataSlicesSlice = ServiceItemHighlightSlice;

/**
 * Content for Servicos documents
 */
interface ServicesDocumentData {
  /**
   * Título da Página field in *Servicos*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTitle: prismic.TitleField;

  /**
   * Descrição da Página field in *Servicos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.pageDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageDescription: prismic.RichTextField;

  /**
   * Slice Zone field in *Servicos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Description field in *Servicos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Servicos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Servicos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Servicos document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | BlogPostDocument
  | ContactDocument
  | FaqDocument
  | FooterDocument
  | GlobalNavbarDocument
  | HomeDocument
  | MaterialDocument
  | PortfolioDocument
  | PortfolioPostDocument
  | ServicesDocument;

/**
 * Primary content in *AboutUsArchitect → Items*
 */
export interface AboutUsArchitectSliceDefaultItem {
  /**
   * Name field in *AboutUsArchitect → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_architect.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Description field in *AboutUsArchitect → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_architect.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * URL field in *AboutUsArchitect → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_architect.items[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * image field in *AboutUsArchitect → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_architect.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutUsArchitect Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsArchitectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<AboutUsArchitectSliceDefaultItem>
>;

/**
 * Slice variation for *AboutUsArchitect*
 */
type AboutUsArchitectSliceVariation = AboutUsArchitectSliceDefault;

/**
 * AboutUsArchitect Shared Slice
 *
 * - **API ID**: `about_us_architect`
 * - **Description**: AboutUsArchitect
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsArchitectSlice = prismic.SharedSlice<
  "about_us_architect",
  AboutUsArchitectSliceVariation
>;

/**
 * Primary content in *AboutUsItem → Default → Primary*
 */
export interface AboutUsItemSliceDefaultPrimary {
  /**
   * Ícone do Item de Quem Somos field in *AboutUsItem → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_item.default.primary.aboutUsItemIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aboutUsItemIcon: prismic.ImageField<never>;

  /**
   * Título do Item de Quem Somos field in *AboutUsItem → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título do Item de Quem Somos
   * - **API ID Path**: about_us_item.default.primary.aboutUsItemTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  aboutUsItemTitle: prismic.TitleField;

  /**
   * Descrição do Item de Quem Somos field in *AboutUsItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_item.default.primary.aboutUsItemDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  aboutUsItemDescription: prismic.RichTextField;
}

/**
 * Default variation for AboutUsItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsItem*
 */
type AboutUsItemSliceVariation = AboutUsItemSliceDefault;

/**
 * AboutUsItem Shared Slice
 *
 * - **API ID**: `about_us_item`
 * - **Description**: AboutUsItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsItemSlice = prismic.SharedSlice<
  "about_us_item",
  AboutUsItemSliceVariation
>;

/**
 * Primary content in *FaqQuestion → Default → Primary*
 */
export interface FaqQuestionSliceDefaultPrimary {
  /**
   * Título da Pergunta field in *FaqQuestion → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título da Pergunta
   * - **API ID Path**: faq_question.default.primary.questionTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  questionTitle: prismic.TitleField;

  /**
   * Resposta da Pergunta field in *FaqQuestion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Resposta da Pergunta
   * - **API ID Path**: faq_question.default.primary.questionAnswer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  questionAnswer: prismic.RichTextField;
}

/**
 * Default variation for FaqQuestion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqQuestionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqQuestionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqQuestion*
 */
type FaqQuestionSliceVariation = FaqQuestionSliceDefault;

/**
 * FaqQuestion Shared Slice
 *
 * - **API ID**: `faq_question`
 * - **Description**: FaqQuestion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqQuestionSlice = prismic.SharedSlice<
  "faq_question",
  FaqQuestionSliceVariation
>;

/**
 * Primary content in *SocialMedia → Default → Primary*
 */
export interface FooterLinkSliceDefaultPrimary {
  /**
   * Imagem do Link field in *SocialMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_link.default.primary.linkImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  linkImage: prismic.ImageField<never>;

  /**
   * Link para Redirecionamento field in *SocialMedia → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_link.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for SocialMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialMedia*
 */
type FooterLinkSliceVariation = FooterLinkSliceDefault;

/**
 * SocialMedia Shared Slice
 *
 * - **API ID**: `footer_link`
 * - **Description**: FooterLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinkSlice = prismic.SharedSlice<
  "footer_link",
  FooterLinkSliceVariation
>;

/**
 * Primary content in *HeroAnimatedImage → Items*
 */
export interface HeroAnimatedImageSliceDefaultItem {
  /**
   * Image field in *HeroAnimatedImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_animated_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroAnimatedImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroAnimatedImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<HeroAnimatedImageSliceDefaultItem>
>;

/**
 * Slice variation for *HeroAnimatedImage*
 */
type HeroAnimatedImageSliceVariation = HeroAnimatedImageSliceDefault;

/**
 * HeroAnimatedImage Shared Slice
 *
 * - **API ID**: `hero_animated_image`
 * - **Description**: HeroAnimatedImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroAnimatedImageSlice = prismic.SharedSlice<
  "hero_animated_image",
  HeroAnimatedImageSliceVariation
>;

/**
 * Primary content in *MaterialItem → Default → Primary*
 */
export interface MaterialItemSliceDefaultPrimary {
  /**
   * Título do Material field in *MaterialItem → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título do Material
   * - **API ID Path**: material_item.default.primary.materialTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  materialTitle: prismic.TitleField;

  /**
   * Descrição do Material field in *MaterialItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do Material
   * - **API ID Path**: material_item.default.primary.materialDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  materialDescription: prismic.RichTextField;

  /**
   * Imagem do Material field in *MaterialItem → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: material_item.default.primary.materialImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  materialImage: prismic.ImageField<never>;

  /**
   * Documento em si field in *MaterialItem → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: material_item.default.primary.materialLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  materialLink: prismic.LinkToMediaField;
}

/**
 * Default variation for MaterialItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MaterialItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MaterialItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MaterialItem*
 */
type MaterialItemSliceVariation = MaterialItemSliceDefault;

/**
 * MaterialItem Shared Slice
 *
 * - **API ID**: `material_item`
 * - **Description**: MaterialItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MaterialItemSlice = prismic.SharedSlice<
  "material_item",
  MaterialItemSliceVariation
>;

/**
 * Primary content in *MetodologyItem → Default → Primary*
 */
export interface MetodologyCardsSliceDefaultPrimary {
  /**
   * Imagem da Metodologia field in *MetodologyItem → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metodology_cards.default.primary.metodologyImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  metodologyImage: prismic.ImageField<never>;

  /**
   * Título da Metodologia field in *MetodologyItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Título da Metodologia
   * - **API ID Path**: metodology_cards.default.primary.metodologyTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  metodologyTitle: prismic.RichTextField;

  /**
   * Descrição da Metodologia Pequena field in *MetodologyItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da Metodologia Pequena
   * - **API ID Path**: metodology_cards.default.primary.metodologyDescriptionTiny
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  metodologyDescriptionTiny: prismic.RichTextField;

  /**
   * Descrição da Metodologia Longa field in *MetodologyItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da Metodologia Longa
   * - **API ID Path**: metodology_cards.default.primary.metodologyDescriptionLong
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  metodologyDescriptionLong: prismic.RichTextField;
}

/**
 * Default variation for MetodologyItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetodologyCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MetodologyCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MetodologyItem*
 */
type MetodologyCardsSliceVariation = MetodologyCardsSliceDefault;

/**
 * MetodologyItem Shared Slice
 *
 * - **API ID**: `metodology_cards`
 * - **Description**: MetodologyCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MetodologyCardsSlice = prismic.SharedSlice<
  "metodology_cards",
  MetodologyCardsSliceVariation
>;

/**
 * Primary content in *PortfolioItemImage → Default → Primary*
 */
export interface PortfolioItemImageSliceDefaultPrimary {
  /**
   * Imagem do Item de Portfólio 1 field in *PortfolioItemImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_item_image.default.primary.portfolioItemImage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolioItemImage1: prismic.ImageField<never>;

  /**
   * Imagem do Item de Portfólio 2 field in *PortfolioItemImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_item_image.default.primary.portfolioItemImage2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolioItemImage2: prismic.ImageField<never>;

  /**
   * Imagem do Item de Portfólio 3 field in *PortfolioItemImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_item_image.default.primary.portfolioItemImage3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolioItemImage3: prismic.ImageField<never>;

  /**
   * Imagem do Item de Portfólio 4 field in *PortfolioItemImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_item_image.default.primary.portfolioItemImage4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolioItemImage4: prismic.ImageField<never>;

  /**
   * Imagem do Item de Portfólio 5 field in *PortfolioItemImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_item_image.default.primary.portfolioItemImage5
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolioItemImage5: prismic.ImageField<never>;
}

/**
 * Default variation for PortfolioItemImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioItemImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioItemImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PortfolioItemImage*
 */
type PortfolioItemImageSliceVariation = PortfolioItemImageSliceDefault;

/**
 * PortfolioItemImage Shared Slice
 *
 * - **API ID**: `portfolio_item_image`
 * - **Description**: PortfolioItemImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioItemImageSlice = prismic.SharedSlice<
  "portfolio_item_image",
  PortfolioItemImageSliceVariation
>;

/**
 * Primary content in *ServiceItemHighlight → Default → Primary*
 */
export interface ServiceItemHighlightSliceDefaultPrimary {
  /**
   * Imagem do Serviço field in *ServiceItemHighlight → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_item_highlight.default.primary.serviceImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  serviceImage: prismic.ImageField<never>;

  /**
   * Título do Serviço field in *ServiceItemHighlight → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: service_item_highlight.default.primary.serviceTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  serviceTitle: prismic.TitleField;

  /**
   * Descrição do Serviço Longa field in *ServiceItemHighlight → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do Serviço Longa
   * - **API ID Path**: service_item_highlight.default.primary.serviceDescriptionLong
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  serviceDescriptionLong: prismic.RichTextField;
}

/**
 * Default variation for ServiceItemHighlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceItemHighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceItemHighlightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceItemHighlight*
 */
type ServiceItemHighlightSliceVariation = ServiceItemHighlightSliceDefault;

/**
 * ServiceItemHighlight Shared Slice
 *
 * - **API ID**: `service_item_highlight`
 * - **Description**: ServiceItemHighlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceItemHighlightSlice = prismic.SharedSlice<
  "service_item_highlight",
  ServiceItemHighlightSliceVariation
>;

/**
 * Primary content in *ServiceItemHome → Default → Primary*
 */
export interface ServicesSlicesSliceDefaultPrimary {
  /**
   * Ícone do Serviço field in *ServiceItemHome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_slices.default.primary.serviceIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  serviceIcon: prismic.ImageField<never>;

  /**
   * Título do Serviço field in *ServiceItemHome → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Título do Serviço
   * - **API ID Path**: services_slices.default.primary.serviceTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  serviceTitle: prismic.TitleField;

  /**
   * Descrição do Serviço Pequena field in *ServiceItemHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição do Serviço Pequena
   * - **API ID Path**: services_slices.default.primary.serviceDescriptionTiny
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  serviceDescriptionTiny: prismic.RichTextField;
}

/**
 * Default variation for ServiceItemHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSlicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceItemHome*
 */
type ServicesSlicesSliceVariation = ServicesSlicesSliceDefault;

/**
 * ServiceItemHome Shared Slice
 *
 * - **API ID**: `services_slices`
 * - **Description**: ServicesSlices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlicesSlice = prismic.SharedSlice<
  "services_slices",
  ServicesSlicesSliceVariation
>;

/**
 * Primary content in *SocialMediaContactPage → Default → Primary*
 */
export interface SocialMediaContactPageSliceDefaultPrimary {
  /**
   * Imagem do Link (Normal) field in *SocialMediaContactPage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_contact_page.default.primary.linkImageNormal
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  linkImageNormal: prismic.ImageField<never>;

  /**
   * Imagem do Link (Hover) field in *SocialMediaContactPage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_contact_page.default.primary.linkImageHover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  linkImageHover: prismic.ImageField<never>;

  /**
   * Link para Redirecionamento field in *SocialMediaContactPage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_contact_page.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for SocialMediaContactPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaContactPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialMediaContactPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialMediaContactPage*
 */
type SocialMediaContactPageSliceVariation = SocialMediaContactPageSliceDefault;

/**
 * SocialMediaContactPage Shared Slice
 *
 * - **API ID**: `social_media_contact_page`
 * - **Description**: SocialMediaContactPage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaContactPageSlice = prismic.SharedSlice<
  "social_media_contact_page",
  SocialMediaContactPageSliceVariation
>;

/**
 * Primary content in *Statements → Default → Primary*
 */
export interface StatementsSliceDefaultPrimary {
  /**
   * Testemunho do Cliente field in *Statements → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Testemunho do Cliente
   * - **API ID Path**: statements.default.primary.clientStatement
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  clientStatement: prismic.RichTextField;

  /**
   * Foto do Cliente field in *Statements → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: statements.default.primary.clientPhoto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  clientPhoto: prismic.ImageField<never>;

  /**
   * Nome do Cliente field in *Statements → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Nome do Cliente
   * - **API ID Path**: statements.default.primary.clientName
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  clientName: prismic.RichTextField;

  /**
   * Papel do Cliente field in *Statements → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Papel do Cliente
   * - **API ID Path**: statements.default.primary.clientRole
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  clientRole: prismic.RichTextField;
}

/**
 * Default variation for Statements Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatementsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statements*
 */
type StatementsSliceVariation = StatementsSliceDefault;

/**
 * Statements Shared Slice
 *
 * - **API ID**: `statements`
 * - **Description**: Statements
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatementsSlice = prismic.SharedSlice<
  "statements",
  StatementsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      GlobalNavbarDocument,
      GlobalNavbarDocumentData,
      GlobalNavbarDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MaterialDocument,
      MaterialDocumentData,
      MaterialDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      PortfolioPostDocument,
      PortfolioPostDocumentData,
      PortfolioPostDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsArchitectSlice,
      AboutUsArchitectSliceDefaultItem,
      AboutUsArchitectSliceVariation,
      AboutUsArchitectSliceDefault,
      AboutUsItemSlice,
      AboutUsItemSliceDefaultPrimary,
      AboutUsItemSliceVariation,
      AboutUsItemSliceDefault,
      FaqQuestionSlice,
      FaqQuestionSliceDefaultPrimary,
      FaqQuestionSliceVariation,
      FaqQuestionSliceDefault,
      FooterLinkSlice,
      FooterLinkSliceDefaultPrimary,
      FooterLinkSliceVariation,
      FooterLinkSliceDefault,
      HeroAnimatedImageSlice,
      HeroAnimatedImageSliceDefaultItem,
      HeroAnimatedImageSliceVariation,
      HeroAnimatedImageSliceDefault,
      MaterialItemSlice,
      MaterialItemSliceDefaultPrimary,
      MaterialItemSliceVariation,
      MaterialItemSliceDefault,
      MetodologyCardsSlice,
      MetodologyCardsSliceDefaultPrimary,
      MetodologyCardsSliceVariation,
      MetodologyCardsSliceDefault,
      PortfolioItemImageSlice,
      PortfolioItemImageSliceDefaultPrimary,
      PortfolioItemImageSliceVariation,
      PortfolioItemImageSliceDefault,
      ServiceItemHighlightSlice,
      ServiceItemHighlightSliceDefaultPrimary,
      ServiceItemHighlightSliceVariation,
      ServiceItemHighlightSliceDefault,
      ServicesSlicesSlice,
      ServicesSlicesSliceDefaultPrimary,
      ServicesSlicesSliceVariation,
      ServicesSlicesSliceDefault,
      SocialMediaContactPageSlice,
      SocialMediaContactPageSliceDefaultPrimary,
      SocialMediaContactPageSliceVariation,
      SocialMediaContactPageSliceDefault,
      StatementsSlice,
      StatementsSliceDefaultPrimary,
      StatementsSliceVariation,
      StatementsSliceDefault,
    };
  }
}
