// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_item: dynamic(() => import("./AboutUsItem")),
  faq_question: dynamic(() => import("./FaqQuestion")),
  footer_link: dynamic(() => import("./SocialMedia")),
  material_item: dynamic(() => import("./MaterialItem")),
  metodology_cards: dynamic(() => import("./MetodologyItem")),
  portfolio_item_image: dynamic(() => import("./PortfolioItemImage")),
  service_item_highlight: dynamic(() => import("./ServiceItemHighlight")),
  services_slices: dynamic(() => import("./ServiceItemHome")),
  social_media_contact_page: dynamic(() => import("./SocialMediaContactPage")),
  statements: dynamic(() => import("./Statements")),
};
